### PR TITLE
Added bbhw written in Common Lisp.

### PR DESCRIPTION
**Pull request by sthames42**

### CODE REVIEW

**Comment by c4augustus** [comment]
Because this is a specific implementation of Common Lisp let's change the directory of this to: code/commonlisp/clisp. And if we do an SBCL implementation then it will be code/commonlisp/sbcl. This is what I did with the different implementations of Scheme.

**Review by c4augustus — CHANGES_REQUESTED** [review]
Because this is a specific implementation of Common Lisp let's change the directory of this to: code/commonlisp/clisp. And if we do an SBCL implementation then it will be code/commonlisp/sbcl. This is what I did with the different implementations of Scheme.

**Review by c4augustus — COMMENTED** [review]
clisp does not build on macOS because the setenv script gives this error "./setenv: line 11: ${REPLY^^}: bad substitution", probably because macOS switched from bash to zsh, which is also why I have been rewriting my bash scripts to be POSIX (simply /bin/sh) compliant.

When I try to build on WSL 1, I get an endless loop of errors during make of "Trying to make room through a GC... Cannot map memory to address 0x80097d188000 . [../src/spvw_mmap.d:347] errno = ENOMEM: Not enough memory."

I recommend using SBCL instead of CLISP. The GNU Software is really problematic.

Finally, feel free to approve your own PRs as you see fit. You don't need my permission.

**Comment by sthames42** [comment]
I can't test under MacOS or WSL1. In the future, I'll see about standardizing on POSIX but there is a problem with my approach to adding REPL access to PATH. `$(dirname $0)` returns the path of the shell (sh,bash,etc.) and not the script if you dot-source the script from the shell. I'll try to find a solution to this, later.

**Pull request merged**
