### PR TITLE
Added Chapel version.

### PR DESCRIPTION
**Pull request by lonetech**
[Chapel](https://chapel-lang.org/) is a language targeting high performance computation. It features distributed computing, including onto GPUs and other hosts, and tunable allocation of subpartitions of arrays. None of which helps it at all with Bye Bye Hello World. Instead, we get to exercise some IO error handling.

### CODE REVIEW

**Comment by c4augustus** [comment]
Interesting language. However when I tried run to build it, your "make -j$(nproc)" locked up my macOS by using every available core. I recommend not calling make with -j. Change that and then if I can run it I will approve the PR. Thanks.

**Review by c4augustus — CHANGES_REQUESTED** [review]
Interesting language. However when I tried run to build it, your "make -j$(nproc)" locked up my macOS by using every available core. I recommend not calling make with -j. Also, the text prompts do not match the previous BBHW spec " Count? " instead of "countdown: " and " Bad Count" instead of "Invalid countdown ". Thanks.

**Comment by lonetech** [comment]
Sorry about that fork bomb, it was not intentional. `nproc` may have failed, causing `make` to start all runnable jobs at once. On my laptop, a serial build took 9m20s, versus a parallel 1m41s. I simply got impatient. Similarly, the run script does a make-style check to not recompile needlessly, as the compilation took about 10s. 

Adjusted the messages also.

**Review by c4augustus — CHANGES_REQUESTED** [review]
Chapel builds on macOS and WSL 1 and the bbhw executable runs fine when called directly. But the run script "which" does not support argument "-s" on WSL 1 (Ubuntu 18.04) and the call to setchplenv.bash spams output to the console before the "countdown: " prompt. Once the run script is fixed this PR will be approved. Thanks.

./bbhw 2
World, Hello...2...1...Bye Bye.

./run 2
Setting CHPL_HOME to /Users/humano/z/v/d/es/plb/bbhw/code/chapel/chapel-2.1.0
Updating PATH to include /Users/humano/z/v/d/es/plb/bbhw/code/chapel/chapel-2.1.0/bin/darwin-arm64
                     and /Users/humano/z/v/d/es/plb/bbhw/code/chapel/chapel-2.1.0/util
Updating MANPATH to include /Users/humano/z/v/d/es/plb/bbhw/code/chapel/chapel-2.1.0/man
Setting CHPL_COMM to none
Setting CHPL_TASKS to fifo
Setting CHPL_MEM to cstdlib
Setting CHPL_HOST_MEM to cstdlib
Setting CHPL_GMP to none
Setting CHPL_RE2 to none
Setting CHPL_LLVM to none
World, Hello...2...1...Bye Bye.

**Review by c4augustus — APPROVED** [review]

**Pull request merged**
